Repository Feminine-Divine/Woodog, pull requests merged in 2021-07, with the labels that each got.

#106 custom scrollbar
  Woodog/templates/partials/base_auth.html
  Woodog/templates/partials/header.html
Labels: LGMSOC21, 🟨 Level2

#105 Made webpages responsive
  Woodog/templates/authentication/login.html
  Woodog/templates/authentication/register.html
  Woodog/templates/partials/_messages.html
  Woodog/templates/partials/footer.html
  Woodog/templates/partials/header.html
  Woodog/templates/woodogdata/about.html
  Woodog/templates/woodogdata/contact.html
  Woodog/templates/woodogdata/index.html
Labels: LGMSOC21, 🟥 Level4

#103 blog page
  Woodog/templates/partials/footer.html
  Woodog/templates/partials/header.html
  Woodog/templates/woodogdata/blog.html
  Woodog/woodogdata/urls.py
  Woodog/woodogdata/views.py
Labels: LGMSOC21, 🟧 Level3

#95 Saup21
  Woodog/authentication/migrations/0003_auto_20210620_0215.py
  Woodog/authentication/migrations/0005_merge_20210624_1625.py
  Woodog/templates/partials/base.html
  Woodog/woodogdata/admin.py
  Woodog/woodogdata/migrations/0001_initial.py
  Woodog/woodogdata/migrations/0002_auto_20210624_1738.py
  Woodog/woodogdata/models.py
Labels: LGMSOC21, 🟥 Level4

#112 Added gallery page
  Woodog/templates/partials/base.html
  Woodog/templates/partials/footer.html
  Woodog/templates/partials/header.html
  Woodog/woodogdata/urls.py
  Woodog/woodogdata/views.py
Labels: LGMSOC21

#117 Made responsive navbar
  Woodog/templates/partials/header.html
Labels: LGMSOC21, 🟧 Level3

#121 adding levels in readme.md file
  README.md
Labels: LGMSOC21, 🟩 Level1

#124 Enhanced Blog page
  Woodog/Woodog/static/img/calendar-blog.svg
  Woodog/Woodog/static/img/caurosel-img.png
  Woodog/Woodog/static/img/comment-blog.svg
  Woodog/Woodog/static/img/editor-img1.png
  Woodog/Woodog/static/img/editor-img2.png
  Woodog/Woodog/static/img/gallery/img1.jpg
  Woodog/Woodog/static/img/gallery/img10.jpg
  Woodog/Woodog/static/img/gallery/img11.jpg
  Woodog/Woodog/static/img/gallery/img12.jpg
  Woodog/Woodog/static/img/gallery/img13.jpg
  Woodog/Woodog/static/img/gallery/img14.jpg
  Woodog/Woodog/static/img/gallery/img15.jpg
  Woodog/Woodog/static/img/gallery/img16.jpg
  Woodog/Woodog/static/img/gallery/img17.webp
  Woodog/Woodog/static/img/gallery/img18.jpg
  Woodog/Woodog/static/img/gallery/img19.jpg
  Woodog/Woodog/static/img/gallery/img2.jpg
  Woodog/Woodog/static/img/gallery/img20.jpg
  Woodog/Woodog/static/img/gallery/img21.jpg
  Woodog/Woodog/static/img/gallery/img22.jpg
  Woodog/Woodog/static/img/gallery/img23.jpg
  Woodog/Woodog/static/img/gallery/img24.jpg
  Woodog/Woodog/static/img/gallery/img25.jpg
  Woodog/Woodog/static/img/gallery/img26.jpg
  Woodog/Woodog/static/img/gallery/img27.jpg
  Woodog/Woodog/static/img/gallery/img28.jpg
  Woodog/Woodog/static/img/gallery/img29.jpg
  Woodog/Woodog/static/img/gallery/img3.jpg
  Woodog/Woodog/static/img/gallery/img30.jpg
  Woodog/Woodog/static/img/gallery/img31.jpg
  Woodog/Woodog/static/img/gallery/img4.jpg
  Woodog/Woodog/static/img/gallery/img5.jpg
  Woodog/Woodog/static/img/gallery/img6.jpg
  Woodog/Woodog/static/img/gallery/img7.jpeg
  Woodog/Woodog/static/img/gallery/img8.jpg
  Woodog/Woodog/static/img/gallery/img9.jpg
  Woodog/Woodog/static/img/pop-calendar.svg
  Woodog/Woodog/static/img/pop-comment.svg
  Woodog/Woodog/static/img/pop-profile.svg
  Woodog/Woodog/static/img/popular-post-2.png
  Woodog/Woodog/static/img/popular-post-3.png
  Woodog/Woodog/static/img/popular-post1.png
  Woodog/Woodog/static/img/post-img1.png
  Woodog/Woodog/static/img/profile -blog.svg
  Woodog/templates/partials/base.html
  Woodog/templates/partials/header.html
  Woodog/templates/woodogdata/blog.html
  Woodog/templates/woodogdata/gallery.html
Labels: LGMSOC21, 🟥 Level4

#126 service page
  Woodog/Woodog/static/img/images (1).jfif
  Woodog/Woodog/static/img/images (2).jfif
  Woodog/Woodog/static/img/images (3).jfif
  Woodog/Woodog/static/img/images.jfif
  Woodog/Woodog/static/img/pet.png
  Woodog/Woodog/static/img/setting1.jpg
  Woodog/Woodog/static/img/setting2.jpg
  Woodog/Woodog/static/img/training.png
  Woodog/Woodog/static/img/training1.jfif
  Woodog/Woodog/static/img/training2.jpg
  Woodog/Woodog/static/img/training3.jpg
  Woodog/Woodog/static/img/walking.png
  Woodog/templates/partials/header.html
  Woodog/templates/woodogdata/index.html
  Woodog/templates/woodogdata/service.html
  Woodog/woodogdata/urls.py
  Woodog/woodogdata/views.py
Labels: LGMSOC21, 🟥 Level4

#128 Enhanced and made FAQ page responsive
  Woodog/templates/woodogdata/FAQ.html
Labels: LGMSOC21, 🟧 Level3

#109 Rest Api in contact us
  Woodog/.gitignore
  Woodog/Woodog/settings.py
  Woodog/api_tester.py
  Woodog/requirements.txt
  Woodog/templates/dashboard/dashboard.html
  Woodog/templates/partials/base.html
  Woodog/templates/woodogdata/conactform_succes.html
  Woodog/templates/woodogdata/contact_us.html
  Woodog/templates/woodogdata/index.html
  Woodog/woodogdata/admin.py
  Woodog/woodogdata/forms.py
  Woodog/woodogdata/models.py
  Woodog/woodogdata/serializers.py
  Woodog/woodogdata/urls.py
  Woodog/woodogdata/views.py
Labels: LGMSOC21, 🟥 Level4

#135 Added chatbot
  Woodog/templates/partials/base.html
Labels: LGMSOC21, 🟥 Level4

#133 Added forgot password functionality
  Woodog/Woodog/settings.py
  Woodog/authentication/urls.py
  Woodog/authentication/views.py
  Woodog/templates/authentication/forget_password.html
  Woodog/templates/authentication/login.html
  Woodog/templates/authentication/reset-password.html
Labels: LGMSOC21, 🟥 Level4

#144 fixed service page
  Woodog/templates/woodogdata/about.html
  Woodog/templates/woodogdata/contact.html
  Woodog/templates/woodogdata/service.html
Labels: LGMSOC21, 🟧 Level3

#132 Feedback Page #70
  Woodog/Woodog/static/css/style.css
  Woodog/feedback-word-and-people-networking-online-cartoon-vector-265550051.png
  Woodog/templates/partials/base.html
  Woodog/templates/partials/feedback.html
Labels: LGMSOC21, 🟥 Level4

#145 Designed Blog content page
  Woodog/Woodog/static/img/comment-profile.svg
  Woodog/Woodog/static/img/next-post.svg
  Woodog/Woodog/static/img/prev-post.svg
  Woodog/templates/woodogdata/blog-content.html
  Woodog/templates/woodogdata/blog.html
  Woodog/woodogdata/urls.py
  Woodog/woodogdata/views.py
Labels: LGMSOC21, 🟥 Level4

#151 Enhanced login page
  Woodog/Woodog/static/img/login.png
  Woodog/templates/authentication/login.html
  Woodog/templates/partials/base.html
  Woodog/templates/partials/header.html
  Woodog/templates/woodogdata/feedback.html
  Woodog/woodogdata/urls.py
  Woodog/woodogdata/views.py
Labels: LGMSOC21, 🟧 Level3

#143 Added Gallery model
  Woodog/Woodog/settings.py
  Woodog/Woodog/urls.py
  Woodog/woodogdata/admin.py
  Woodog/woodogdata/migrations/0003_gallery.py
  Woodog/woodogdata/migrations/0004_auto_20210711_2106.py
  Woodog/woodogdata/models.py
Labels: LGMSOC21, 🟥 Level4

#149 Added Blog Model
  Woodog/Woodog/settings.py
  Woodog/Woodog/urls.py
  Woodog/requirements.txt
  Woodog/woodogdata/admin.py
  Woodog/woodogdata/helpers.py
  Woodog/woodogdata/migrations/0003_blogmodel.py
  Woodog/woodogdata/migrations/0004_auto_20210712_1902.py
  Woodog/woodogdata/migrations/0005_auto_20210712_1941.py
  Woodog/woodogdata/models.py
Labels: LGMSOC21, 🟥 Level4

#157 register page updated
  Woodog/templates/authentication/register.html
Labels: LGMSOC21, 🟨 Level2

#153 Added sign in using Google
  Woodog/Woodog/settings.py
  Woodog/Woodog/static/img/google-plus.svg
  Woodog/Woodog/urls.py
  Woodog/requirements.txt
  Woodog/templates/authentication/login.html
  Woodog/templates/authentication/register.html
Labels: LGMSOC21, 🟥 Level4

#158 Added functions for fetching images
  Woodog/templates/woodogdata/gallery.html
  Woodog/woodogdata/migrations/0006_merge_20210718_2202.py
  Woodog/woodogdata/migrations/0007_auto_20210719_0913.py
  Woodog/woodogdata/migrations/0008_auto_20210719_0914.py
  Woodog/woodogdata/models.py
  Woodog/woodogdata/views.py
Labels: LGMSOC21, 🟥 Level4

#164 created add blogs page
  Woodog/Woodog/settings.py
  Woodog/templates/woodogdata/add-blog.html
  Woodog/templates/woodogdata/blog.html
  Woodog/templates/woodogdata/contact.html
  Woodog/woodogdata/migrations/0009_auto_20210723_0936.py
  Woodog/woodogdata/migrations/0010_auto_20210723_1607.py
  Woodog/woodogdata/models.py
  Woodog/woodogdata/urls.py
  Woodog/woodogdata/views.py
Labels: LGMSOC21, 🟥 Level4

#163 Fixed the height bug in Chatbot
  Woodog/templates/partials/base.html
Labels: LGMSOC21, 🟧 Level3

#159 Added fetch data from blog model
  Woodog/Woodog/urls.py
  Woodog/requirements.txt
  Woodog/templates/woodogdata/blog.html
  Woodog/templates/woodogdata/blog_content.html
  Woodog/woodogdata/helpers.py
  Woodog/woodogdata/migrations/0006_merge_20210719_1100.py
  Woodog/woodogdata/migrations/0007_auto_20210719_1120.py
  Woodog/woodogdata/migrations/0008_auto_20210719_1547.py
  Woodog/woodogdata/migrations/0009_auto_20210719_1644.py
  Woodog/woodogdata/models.py
  Woodog/woodogdata/urls.py
  Woodog/woodogdata/views.py
Labels: LGMSOC21, 🟥 Level4
