Repository Feminine-Divine/Woodog, pull requests merged in 2021-06, with the labels that each got.

#8 created contributing.md file
  README.md
  contributing.md
Labels: LGMSOC21, 🟨 Level2

#14 Changed database to sqlite
  Woodog/.gitignore
  Woodog/Woodog/__pycache__/__init__.cpython-38.pyc
  Woodog/Woodog/__pycache__/settings.cpython-38.pyc
  Woodog/Woodog/__pycache__/urls.cpython-38.pyc
  Woodog/Woodog/__pycache__/wsgi.cpython-38.pyc
  Woodog/Woodog/settings.py
  Woodog/appdashboard/__pycache__/__init__.cpython-38.pyc
  Woodog/appdashboard/__pycache__/admin.cpython-38.pyc
  Woodog/appdashboard/__pycache__/models.cpython-38.pyc
  Woodog/appdashboard/__pycache__/urls.cpython-38.pyc
  Woodog/appdashboard/__pycache__/views.cpython-38.pyc
  Woodog/appdashboard/migrations/__pycache__/__init__.cpython-38.pyc
  Woodog/authentication/__pycache__/__init__.cpython-38.pyc
  Woodog/authentication/__pycache__/admin.cpython-38.pyc
  Woodog/authentication/__pycache__/models.cpython-38.pyc
  Woodog/authentication/__pycache__/urls.cpython-38.pyc
  Woodog/authentication/__pycache__/utils.cpython-38.pyc
  Woodog/authentication/__pycache__/views.cpython-38.pyc
  Woodog/authentication/migrations/__pycache__/__init__.cpython-38.pyc
  Woodog/woodogdata/__pycache__/__init__.cpython-38.pyc
  Woodog/woodogdata/__pycache__/admin.cpython-38.pyc
  Woodog/woodogdata/__pycache__/models.cpython-38.pyc
  Woodog/woodogdata/__pycache__/urls.cpython-38.pyc
  Woodog/woodogdata/__pycache__/views.cpython-38.pyc
  Woodog/woodogdata/migrations/__pycache__/__init__.cpython-38.pyc
Labels: LGMSOC21, 🟥 Level4

#16 Rename and Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: LGMSOC21, 🟨 Level2

#18 Created documentation issue template
  .github/ISSUE_TEMPLATE/documentation.md
Labels: LGMSOC21, documentation, 🟨 Level2

#28 Program Section Added #24
  README.md
Labels: LGMSOC21

#29 Create LICENSE
  LICENSE
Labels: LGMSOC21, 🟨 Level2

#32 update readme
  README.md
Labels: LGMSOC21, 🟨 Level2

#33 README updated and pycache and sqlite3 added to gitignore
  README.md
  Woodog/.gitignore
  Woodog/Woodog/__pycache__/__init__.cpython-38.pyc
  Woodog/Woodog/__pycache__/__init__.cpython-39.pyc
  Woodog/Woodog/__pycache__/settings.cpython-38.pyc
  Woodog/Woodog/__pycache__/settings.cpython-39.pyc
  Woodog/Woodog/__pycache__/urls.cpython-38.pyc
  Woodog/Woodog/__pycache__/urls.cpython-39.pyc
  Woodog/Woodog/__pycache__/wsgi.cpython-38.pyc
  Woodog/Woodog/__pycache__/wsgi.cpython-39.pyc
  Woodog/appdashboard/__pycache__/__init__.cpython-38.pyc
  Woodog/appdashboard/__pycache__/__init__.cpython-39.pyc
  Woodog/appdashboard/__pycache__/admin.cpython-38.pyc
  Woodog/appdashboard/__pycache__/admin.cpython-39.pyc
  Woodog/appdashboard/__pycache__/apps.cpython-39.pyc
  Woodog/appdashboard/__pycache__/models.cpython-38.pyc
  Woodog/appdashboard/__pycache__/models.cpython-39.pyc
  Woodog/appdashboard/__pycache__/urls.cpython-38.pyc
  Woodog/appdashboard/__pycache__/urls.cpython-39.pyc
  Woodog/appdashboard/__pycache__/views.cpython-38.pyc
  Woodog/appdashboard/__pycache__/views.cpython-39.pyc
  Woodog/appdashboard/migrations/__pycache__/__init__.cpython-38.pyc
  Woodog/appdashboard/migrations/__pycache__/__init__.cpython-39.pyc
  Woodog/authentication/__pycache__/__init__.cpython-38.pyc
  Woodog/authentication/__pycache__/__init__.cpython-39.pyc
  Woodog/authentication/__pycache__/admin.cpython-38.pyc
  Woodog/authentication/__pycache__/admin.cpython-39.pyc
  Woodog/authentication/__pycache__/apps.cpython-39.pyc
  Woodog/authentication/__pycache__/models.cpython-38.pyc
  Woodog/authentication/__pycache__/models.cpython-39.pyc
  Woodog/authentication/__pycache__/urls.cpython-38.pyc
  Woodog/authentication/__pycache__/urls.cpython-39.pyc
  Woodog/authentication/__pycache__/utils.cpython-38.pyc
  Woodog/authentication/__pycache__/utils.cpython-39.pyc
  Woodog/authentication/__pycache__/views.cpython-38.pyc
  Woodog/authentication/__pycache__/views.cpython-39.pyc
  Woodog/authentication/migrations/__pycache__/__init__.cpython-38.pyc
  Woodog/authentication/migrations/__pycache__/__init__.cpython-39.pyc
  Woodog/db.sqlite3
  Woodog/woodogdata/__pycache__/__init__.cpython-38.pyc
  Woodog/woodogdata/__pycache__/__init__.cpython-39.pyc
  Woodog/woodogdata/__pycache__/admin.cpython-38.pyc
  Woodog/woodogdata/__pycache__/admin.cpython-39.pyc
  Woodog/woodogdata/__pycache__/apps.cpython-39.pyc
  Woodog/woodogdata/__pycache__/models.cpython-38.pyc
  Woodog/woodogdata/__pycache__/models.cpython-39.pyc
  Woodog/woodogdata/__pycache__/urls.cpython-38.pyc
  Woodog/woodogdata/__pycache__/urls.cpython-39.pyc
  Woodog/woodogdata/__pycache__/views.cpython-38.pyc
  Woodog/woodogdata/__pycache__/views.cpython-39.pyc
  Woodog/woodogdata/migrations/__pycache__/__init__.cpython-38.pyc
  Woodog/woodogdata/migrations/__pycache__/__init__.cpython-39.pyc
Labels: LGMSOC21, documentation, 🟨 Level2

#45 Update README.md
  README.md
Labels: LGMSOC21, 🟪 Level0

#44 Created sign-up page
  Woodog/authentication/urls.py
  Woodog/authentication/views.py
  Woodog/templates/authentication/register.html
  Woodog/templates/partials/base.html
  Woodog/templates/woodogdata/index.html
  Woodog/woodogdata/urls.py
  Woodog/woodogdata/views.py
Labels: LGMSOC21, 🟥 Level4

#62 Logo added to Woodog Directory #25
  Woodog/woodog_logo/WOODOG.png
Labels: LGMSOC21, 🟥 Level4

#72 Issue43
  .github/config.yml
Labels: LGMSOC21, 🟨 Level2

#73 Added Logo1 #61
  Woodog/Woodog/static/img/woodog-logo1.png
  Woodog/templates/partials/base.html
  Woodog/woodog_logo/WOODOG.png
Labels: LGMSOC21, 🟨 Level2

#76 Add files via upload
  .vscode/settings.json
  Woodog-master/CODE_OF_CONDUCT.md
  Woodog-master/CONTRIBUTING.md
  Woodog-master/LICENSE
  Woodog-master/README.md
  Woodog-master/Woodog/appdashboard/admin.py
  Woodog-master/Woodog/appdashboard/apps.py
  Woodog/authentication/migrations/0002_alter_user_status_id.py
  Woodog/authentication/views.py
  Woodog/templates/partials/base.html
  Woodog/templates/woodogdata/index.html
Labels: LGMSOC21, 🟨 Level2

#81 added some badges
  README.md
Labels: LGMSOC21, 🟨 Level2

#69 Added About Us Page
  Woodog/templates/woodogdata/about.html
Labels: LGMSOC21, 🟥 Level4

#82 Refactored the template file structure
  Woodog/Woodog/static/css/style.css
  Woodog/templates/authentication/login.html
  Woodog/templates/authentication/register.html
  Woodog/templates/dashboard/dashboard.html
  Woodog/templates/partials/base.html
  Woodog/templates/partials/footer.html
  Woodog/templates/partials/header.html
  Woodog/templates/woodogdata/index.html
Labels: LGMSOC21, 🟥 Level4

#84 Added Contact Us Page
  Woodog/templates/woodogdata/contact.html
Labels: LGMSOC21, 🟥 Level4

#89 Enhanced the about-us page
  Woodog/Woodog/static/img/about-us-dog1.png
  Woodog/Woodog/static/img/connect.png
  Woodog/Woodog/static/img/dog-care.png
  Woodog/Woodog/static/img/dogs-2.jpg
  Woodog/Woodog/static/img/dogs-eating.jpg
  Woodog/Woodog/static/img/food.png
  Woodog/Woodog/static/img/location-dog.png
  Woodog/Woodog/static/img/shelter.png
  Woodog/templates/woodogdata/about.html
  Woodog/woodogdata/urls.py
  Woodog/woodogdata/views.py
Labels: LGMSOC21, 🟥 Level4

#92 Enhanced the contact page
  Woodog/Woodog/static/img/location.svg
  Woodog/Woodog/static/img/phone.svg
  Woodog/Woodog/static/img/send-msg.svg
  Woodog/templates/authentication/login.html
  Woodog/templates/authentication/register.html
  Woodog/templates/partials/base.html
  Woodog/templates/partials/footer.html
  Woodog/templates/partials/header.html
  Woodog/templates/woodogdata/contact.html
  Woodog/woodogdata/urls.py
  Woodog/woodogdata/views.py
Labels: LGMSOC21, 🟥 Level4

#87 Suggestions updated.
  Woodog/Woodog/settings.py
  Woodog/Woodog/static/css/error.css
  Woodog/authentication/migrations/0003_auto_20210621_2318.py
  Woodog/authentication/urls.py
  Woodog/authentication/views.py
  Woodog/templates/authentication/login.html
  Woodog/templates/authentication/register.html
  Woodog/templates/partials/error_page.html
  Woodog/templates/partials/header.html
  Woodog/templates/woodogdata/index.html
  Woodog/woodogdata/views.py
Labels: LGMSOC21, 🟥 Level4

#94 added scroll to top button
  Woodog/Woodog/static/img/top.svg
  Woodog/authentication/migrations/0004_merge_20210623_2156.py
  Woodog/templates/partials/footer.html
Labels: LGMSOC21, 🟧 Level3

#96 added favicon to website
  Woodog/Woodog/static/img/favicon.png
  Woodog/templates/partials/base.html
Labels: LGMSOC21, 🟧 Level3

#98 Created Change Password page
  Woodog/authentication/urls.py
  Woodog/authentication/views.py
  Woodog/templates/authentication/set-newpassword.html
Labels: LGMSOC21, 🟧 Level3

#100 enhanced alert messages
  Woodog/Woodog/static/js/bootstrap-auto-dismiss-alert.js
  Woodog/templates/partials/_messages.html
  Woodog/templates/partials/base.html
  Woodog/templates/woodogdata/index.html
Labels: LGMSOC21, 🟥 Level4
